---
# task file for ubuntu.yml
- name: nvidia-docker2 release key is registered.
  apt_key: url="{{ apt_key_url }}" state=present

- name: software-properties-common is installed for prerequisite for apt_repository ansible module
  apt: name=software-properties-common state=present